version: "3"

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volume:
      - ./database:/var/lib/postgres/data
    ports:
      - '5432:5432'

  web:
    build: .
    depends_on:
      - db
    ports:
      - '10515:80'
