version: "3.8"

services:

  db:
    build: ./database/
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'word_list'
    ports:
      - '5432:5432'

  web:
    build: ./
    depends_on:
      - db
    ports:
      - '10528:80'
