version: "3"

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/word_list.sql:/docker-entrypoint-initdb.d/word_list.sql
    ports:
      - '5432:5432'

  web:
    build: ./
    depends_on:
      - db
    ports:
      - '10528:80'
